name:                llm-parse
version:             0.1.0.0
github:              "chrisdone/llm-parse"
license:             BSD-3-Clause
author:              "Chris Done"
maintainer:          "chris@chrisdone.com"
copyright:           "2025 Chris Done"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- conduit
- conduit-extra
- http-conduit
- resourcet
- http-types
- text
- aeson
- bytestring
- sse-conduit
- free
- llm-conduit

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  llm-parse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llm-parse
    - hspec
